services:
  bot:
    build:
      network: host
      context: .
    network_mode: host
    restart: always
    environment:
      REDIS_URL: "redis://localhost:${REDIS_PORT}"
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      OPERATOR_TOKEN: ${OPERATOR_TOKEN}

      ADMINS: ${ADMINS}
      ADMINS_1: ${ADMINS_1}
      ADMINS_2: ${ADMINS_2}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_ECHO_LOG: ${DB_ECHO_LOG}

      SERVICE_PORT: ${SERVICE_PORT}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
      WEB_APP_URL: ${WEB_APP_URL}

      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
  redis:
    image: redis:8.2
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data: